# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import uuid

import mysql.connector

import tkinter as tk
from tkinter import ttk
from pathlib import Path
from tkinter import *

# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame, messagebox, font, ttk

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH_FRAME10 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame10")
ASSETS_PATH_FRAME9 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame9")
ASSETS_PATH_FRAME8 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame8")
ASSETS_PATH_FRAME7 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame7")
ASSETS_PATH_FRAME6 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame6")
ASSETS_PATH_FRAME5 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame5")
ASSETS_PATH_FRAME4 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame4")
ASSETS_PATH_FRAME3 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame3")
ASSETS_PATH_FRAME2 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame2")
ASSETS_PATH_FRAME1 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame1")
ASSETS_PATH_FRAME0 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame0")
ASSETS_PATH_FRAME11 = OUTPUT_PATH / Path(r"D:\SLIPD\Z Project\SpareMart\assets\frame11")

try:
    # Establish connection
    connection = mysql.connector.connect(
        host='localhost',
        port=3315,
        user='root',
        passwd='',
        database='sparemart'
    )

    # Check connection
    if connection.is_connected():
        print('Connected to MySQL')

    # Initialize cursor for executing SQL queries
    cursor = connection.cursor()

except:
    print('Error while connecting to MySQL')

def relative_to_assets_frame10(path: str) -> Path:
    return ASSETS_PATH_FRAME10 / Path(path)

def relative_to_assets_frame9(path: str) -> Path:
    return ASSETS_PATH_FRAME9 / Path(path)

def relative_to_assets_frame8(path: str) -> Path:
    return ASSETS_PATH_FRAME8 / Path(path)

def relative_to_assets_frame7(path: str) -> Path:
    return ASSETS_PATH_FRAME7 / Path(path)

def relative_to_assets_frame6(path: str) -> Path:
    return ASSETS_PATH_FRAME6 / Path(path)

def relative_to_assets_frame5(path: str) -> Path:
    return ASSETS_PATH_FRAME5 / Path(path)

def relative_to_assets_frame4(path: str) -> Path:
    return ASSETS_PATH_FRAME4 / Path(path)

def relative_to_assets_frame3(path: str) -> Path:
    return ASSETS_PATH_FRAME3 / Path(path)

def relative_to_assets_frame2(path: str) -> Path:
    return ASSETS_PATH_FRAME2 / Path(path)

def relative_to_assets_frame1(path: str) -> Path:
    return ASSETS_PATH_FRAME1 / Path(path)

def relative_to_assets_frame0(path: str) -> Path:
    return ASSETS_PATH_FRAME0 / Path(path)

def relative_to_assets_frame11(path: str) -> Path:
    return ASSETS_PATH_FRAME11 / Path(path)

def show_frame(frame):
    frame.tkraise()

def delete_data(frame, window):
    for widget in frame.winfo_children():  # Loop through all widgets in the frame
        if isinstance(widget, Entry):  # Check if the widget is an Entry field
            widget.delete(0, 'end')
        window.focus() # Remove focus from any entry widget (It means remove curser)

def go_home(*args):
    entry_9_1.delete(0, "end")
    entry_9_2.delete(0, "end")
    entry_9_3.delete(0, "end")
    entry_9_2.config(show="*")
    button_9_3.config(image=hide_icon)
    entry_9_3.config(show="*")
    button_9_4.config(image=hide_icon)

    entry_8_1.delete(0, "end")
    entry_8_2.delete(0, "end")
    entry_8_2.config(show="*")
    button_8_3.config(image=hide_icon)

    window.focus()
    show_frame(frame10)

def go_dash(entry, window):
    delete_data(entry, window)
    show_frame(frame7)

def go_back(entry1, entry2, window):
    delete_data(entry1, window)
    show_frame(entry2)

    entry_0_1.insert('end', current_user_name)
    entry_0_2.insert('end', current_user_pass)
    entry_0_2.config(show="*")
    button_0_3.config(image=hide_icon)
    update_itembox()
    window.focus()

def password_visibility(entry, button):
    if entry.cget("show") == "*":
        entry.config(show="")  # Show the password
        button.config(image=show_icon)  # Change button to "Hide" image
    else:
        entry.config(show="*")  # Hide the password
        button.config(image=hide_icon)  # Change button to "Show" image

def register_account():
    username = entry_9_1.get()
    password = entry_9_2.get()
    repassword = entry_9_3.get()

    if password == repassword:
        cursor.execute('SELECT name FROM employee WHERE name = %s', (username,))
        existing_user = cursor.fetchone()  # Fetch the result to clear the cursor
        if existing_user:
            messagebox.showwarning("Warning", "The username is already used.")
        else:
            cursor.execute('INSERT INTO employee (name, password) VALUES (%s, %s)', (username, password))
            connection.commit()
            messagebox.showinfo("Registration", "You are registered successfully.")
            show_frame(frame8)
    else:
        print("password mismatch")
        messagebox.showerror("Registration", "Passwords do not match!")

def login_account():
    username = entry_8_1.get()
    password = entry_8_2.get()

    cursor.execute('SELECT id, password FROM employee WHERE name = %s', (username,))
    existing_user = cursor.fetchone()

    if existing_user:
        user_id, stored_password = existing_user
        if stored_password == password:
            #messagebox.showinfo("Login", "You are logged in successfully!")

            show_frame(frame7)

            # Store the username, password, user ID globally if needed
            global old_name
            old_name = username
            global current_user_id
            current_user_id = user_id
            global current_user_name
            current_user_name = username
            global current_user_pass
            current_user_pass = password

            entry_0_1.insert('end', username)
            entry_0_2.insert('end', password)
            entry_0_2.config(show="*")
            button_0_3.config(image=hide_icon)

            update_textbox(username, password)
        else:
            messagebox.showerror("Login", "Wrong password!")
    else:
        messagebox.showwarning("Warning", "You are not registered yet.")

def update_textbox(user_name, user_pass):
    label_7_1.config(text=user_name)
    label_6_1.config(text=user_name)
    label_5_1.config(text=user_name)
    label_4_1.config(text=user_name)
    label_3_1.config(text=user_name)
    label_2_1.config(text=user_name)
    label_1_1.config(text=user_name)
    label_0_1.config(text=user_name)
    label_11_1.config(text=user_name)
    label_11_2.config(text=user_name)
    label_1_3.config(text=user_name)
    label_1_2.config(text='*' * len(user_pass))
    #entry_0_1.insert('end', user_name)
    #entry_0_2.insert('end', user_pass)
    entry_0_2.config(show="*")
    button_0_3.config(image=hide_icon)

def logout_account():
    response1 = messagebox.askyesno("Logout", "Do you want to logout?")
    if response1:
        # Store the username, password, user ID globally if needed
        current_user_id = ""
        current_user_name = ""
        current_user_pass = ""
        show_frame(frame10)
    else:
        show_frame(frame7)

def update_account():
    updateusername = entry_0_1.get()
    updatepassword = entry_0_2.get()
    cursor.execute("UPDATE employee SET name = %s, password = %s WHERE id = %s", (updateusername, updatepassword, current_user_id))
    #cursor.execute("UPDATE spareparts SET owner = %s WHERE owner = %s", (updateusername, old_name))
    connection.commit()

    # Fetch the updated record to verify the update
    cursor.execute('SELECT name, password FROM employee WHERE id = %s', (current_user_id,))
    existing_user = cursor.fetchone()
    if existing_user:
        current_user_name = updateusername
        current_user_pass = updatepassword
        update_textbox(updateusername, updatepassword)
        #change_username(updateusername)
        messagebox.showinfo("Update Account", "Your account has been updated successfully!")
        show_frame(frame11)

    else:
        messagebox.showerror("Update Account", "Updating is unsuccessful!")

def change_username(updateusername):
    old_name = updateusername

def delete_account():
    response1 = messagebox.askyesno("Delete Account", "Do you want to delete the account?")
    if response1:
        response2 = messagebox.askyesno("Delete Account", "Are you sure?")
        if response2:
            messagebox.showwarning("Warning", "Your account has been deleted.")
            cursor.execute("DELETE FROM employee WHERE id = %s", (current_user_id,))
            connection.commit()
            show_frame(frame9)
        else:
            show_frame(frame11)
    else:
        show_frame(frame11)

def read_alldata():
    cursor.execute("SELECT itemCode, itemName, itemType, itemPrice, itemQuantity, description, owner FROM spareparts ")

    # Create the Treeview widget
    tree = ttk.Treeview(frame6)
    tree['show'] = 'headings'

    s = ttk.Style(window)
    s.theme_use('xpnative')

    # Define number of columns
    tree["columns"] = ("itemCode", "itemName", "itemType", "itemPrice", "itemQuantity", "description", "owner")

    # Assign width, minwidth
    tree.column("itemCode", width=100, minwidth=100, anchor=tk.CENTER)
    tree.column("itemName", width=100, minwidth=100, anchor=tk.CENTER)
    tree.column("itemType", width=100, minwidth=100, anchor=tk.CENTER)
    tree.column("itemPrice", width=100, minwidth=100, anchor=tk.CENTER)
    tree.column("itemQuantity", width=100, minwidth=100, anchor=tk.CENTER)
    tree.column("description", width=100, minwidth=100, anchor=tk.CENTER)
    tree.column("owner", width=100, minwidth=100, anchor=tk.CENTER)

    # Assign the heading names
    tree.heading("itemCode", text="Item Code", anchor=tk.CENTER)
    tree.heading("itemName", text="Item Name", anchor=tk.CENTER)
    tree.heading("itemType", text="Item Type", anchor=tk.CENTER)
    tree.heading("itemPrice", text="Item Price", anchor=tk.CENTER)
    tree.heading("itemQuantity", text="Item Quantity", anchor=tk.CENTER)
    tree.heading("description", text="Description", anchor=tk.CENTER)
    tree.heading("owner", text="Owner", anchor=tk.CENTER)

    # Insert rows into the Treeview
    i = 0
    for row in cursor:
        tree.insert('', i, text="", values=(row[0], row[1], row[2], row[3], row[4], row[5], row[6]))
        i += 1

    # Horizontal scrollbar
    hsb = ttk.Scrollbar(frame, orient="horizontal")
    hsb.configure(command=tree.xview)
    tree.configure(xscrollcommand=hsb.set)
    hsb.pack(fill=tk.X, side=tk.BOTTOM)

    # Vertical scrollbar
    vsb = ttk.Scrollbar(frame, orient="vertical")
    vsb.configure(command=tree.yview)
    tree.configure(yscrollcommand=vsb.set)
    vsb.pack(fill=tk.Y, side=tk.RIGHT)

    tree.pack(fill=tk.BOTH, expand=True)
    tree.place(x=99.0, y=183.0, width=1118.0, height=371.0)

def manage_spareparts():
    show_frame(frame6)

def search_item():
    code = entry_6_3.get()
    cursor.execute(
        'SELECT itemCode, itemName, itemType, itemPrice, itemQuantity, description, owner FROM spareparts WHERE itemCode = %s',
        (code,))
    result = cursor.fetchone()  # Fetch a single matching row

    # Check if the result is not None (i.e., an item was found)
    if result:
        itemCode, itemName, itemType, itemPrice, itemQuantity, description, owner = result

        global owneritem
        owneritem = owner

        update_searchbox(itemCode, itemName, itemType, description, itemQuantity, itemPrice)

        update_itembox()
        show_frame(frame3)  # Display frame3 when the item is found

    else:
        # If no result is found, show a warning message
        messagebox.showwarning("Warning", "Item not found!")

def update_searchbox(itemCode, itemName, itemType, description, itemQuantity, itemPrice):
    # Update the labels with the values fetched from the database
    label_3_2.config(text=itemCode)
    label_3_4.config(text=itemName)
    label_3_3.config(text=itemType)
    label_3_5.config(text=description)  # Displaying itemPrice
    label_3_6.config(text=itemQuantity)
    label_3_7.config(text=itemPrice)

    global icode, name, type, des, qty, price

    icode = itemCode
    name = itemName
    type = itemType
    des = description
    qty = itemQuantity
    price = itemPrice

def update_itembox():
    delete_data(frame2, window)
    label_2_2.config(text=icode)
    #entry_2_1.insert(END, icode)
    entry_2_3.insert(END, name)
    entry_2_2.insert(END, type)
    entry_2_4.insert(END, des)
    entry_2_5.insert(END, qty)
    entry_2_6.insert(END, price)

def generate_item_code():
    prefix = "ITEM"
    unique_number = str(uuid.uuid4().int)[:5]  # Use a random 5-digit number from UUID
    global item_code
    item_code =  (f"{prefix}-{unique_number}")

def add_spareparts():
    generate_item_code()
    label_5_2.config(text=item_code)
    show_frame(frame5)

def add_item():
    itemCode = item_code
    itemName = entry_5_3.get()
    itemType = entry_5_2.get()
    itemPrice = entry_5_6.get()
    itemQuantity = entry_5_5.get()
    description = entry_5_4.get()
    owner = current_user_name

    try:
        # Insert the data into the database
        cursor.execute(
            'INSERT INTO spareparts (itemCode, itemName, itemType, itemPrice, itemQuantity, description, owner) '
            'VALUES (%s, %s, %s, %s, %s, %s, %s)',
            (itemCode, itemName, itemType, itemPrice, itemQuantity, description, owner))
        connection.commit()  # Commit the transaction

        # Show success message
        messagebox.showinfo("Add Item", "Your item has been added successfully!")

        # Show the next frame
        show_frame(frame6)
        delete_data(frame5, window)
        read_alldata()

    except mysql.connector.Error as err:
        # If there is an error with the database, show an error message
        messagebox.showerror("Database Error", f"Error: {err}")

def update_item():

    if owneritem == current_user_name:
        update_icode = icode
        update_iname = entry_2_3.get()
        update_itype = entry_2_2.get()
        update_ides = entry_2_4.get()
        update_iqty = entry_2_5.get()
        update_iprice = entry_2_6.get()

        try:
            cursor.execute(
                "UPDATE spareparts SET itemName = %s, itemType = %s, itemPrice = %s, itemQuantity = %s, description = %s WHERE itemCode = %s",
                (update_iname, update_itype, update_iprice, update_iqty, update_ides, update_icode))
            connection.commit()

            messagebox.showinfo("Update Item", "Your item has been updated successfully!")
            update_searchbox(update_icode, update_iname, update_itype, update_ides, update_iqty, update_iprice)
            read_alldata()
            update_itembox()
            show_frame(frame3)

        except mysql.connector.Error as err:
            messagebox.showerror("Database Error", f"Error: {err}")
    else:
        messagebox.showerror("error", "You are not allowed to update this item!")
        go_back(frame2, frame3, window)
        #show_frame(frame3)

def delete_item():
    if owneritem == current_user_name:
        response1 = messagebox.askyesno("Delete Item", "Do you want to delete the item?")
        if response1:
            response2 = messagebox.askyesno("Delete Item", "Are you sure?")
            if response2:
                messagebox.showwarning("Warning", "Item has been deleted.")
                cursor.execute("DELETE FROM spareparts WHERE itemCode = %s", (icode,))
                connection.commit()
                read_alldata()
                show_frame(frame6)
            else:
                show_frame(frame3)
        else:
            show_frame(frame3)

    else:
        messagebox.showerror("error", "You are not allowed to delete this item!")
        show_frame(frame3)


window = Tk()

window.geometry("1300x720")
window.configure(bg = "#FFFFFF")

#Add icon to application
icon = tk.PhotoImage(file='sparemart-removebg-preview.png')
window.iconphoto(True, icon)
window.title("SpareMart")
entry_font = font.Font(family="Arial", size=15)

# Initialize frames
frame10 = Frame(window, bg="#FFFFFF")
frame9 = Frame(window, bg="#FFFFFF")
frame8 = Frame(window, bg="#FFFFFF")
frame7 = Frame(window, bg="#FFFFFF")
frame6 = Frame(window, bg="#FFFFFF")
frame5 = Frame(window, bg="#FFFFFF")
frame4 = Frame(window, bg="#FFFFFF")
frame3 = Frame(window, bg="#FFFFFF")
frame2 = Frame(window, bg="#FFFFFF")
frame1 = Frame(window, bg="#FFFFFF")
frame0 = Frame(window, bg="#FFFFFF")
frame11 = Frame(window, bg="#FFFFFF")

for frame in (frame10, frame9, frame8, frame7, frame6, frame5, frame4, frame3, frame2, frame1, frame0, frame11):
    frame.place(x=0, y=0, width=1300, height=720)

# FRAME 10
canvas10 = Canvas(
    frame10,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas10.place(x = 0, y = 0)
image_image_10_1 = PhotoImage(
    file=relative_to_assets_frame10("image_10_1.png"))
image_10_1 = canvas10.create_image(
    650.0,
    427.0,
    image=image_image_10_1
)

button_image_10_1 = PhotoImage(
    file=relative_to_assets_frame10("button_10_1.png"))
button_10_1 = Button(
    frame10,
    image=button_image_10_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame8),
    relief="flat"
)
button_10_1.place(
    x=420.0,
    y=597.0,
    width=200.0,
    height=66.0
)

button_image_10_2 = PhotoImage(
    file=relative_to_assets_frame10("button_10_2.png"))
button_10_2 = Button(
    frame10,
    image=button_image_10_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame9),
    relief="flat"
)
button_10_2.place(
    x=680.0,
    y=595.0,
    width=200.0,
    height=66.0
)

# FRAME 9
canvas9 = Canvas(
    frame9,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas9.place(x = 0, y = 0)
image_image_9_1 = PhotoImage(
    file=relative_to_assets_frame9("image_9_1.png"))
image_9_1 = canvas9.create_image(
    650.0,
    427.0,
    image=image_image_9_1
)

button_image_9_1 = PhotoImage(
    file=relative_to_assets_frame9("button_9_1.png"))
button_9_1 = Button(
    frame9,
    image=button_image_9_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_home(entry_9_1, entry_9_2, entry_9_3, button_9_3, button_9_4),
    relief="flat"
)
button_9_1.place(
    x=628.0,
    y=600.0,
    width=103.0,
    height=41.0
)

image_image_9_2 = PhotoImage(
    file=relative_to_assets_frame9("image_9_2.png"))
image_9_2 = canvas9.create_image(
    683.0,
    356.0,
    image=image_image_9_2
)

canvas9.create_text(
    640.0,
    157.0,
    anchor="nw",
    text="Sign up",
    fill="#3D3030",
    font=("Inter", 32 * -1)
)

canvas9.create_text(
    524.0,
    212.0,
    anchor="nw",
    text="Username",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas9.create_text(
    524.0,
    314.0,
    anchor="nw",
    text="Password",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

image_image_9_3 = PhotoImage(
    file=relative_to_assets_frame9("image_9_3.png"))
image_9_3 = canvas9.create_image(
    620.0,
    177.0,
    image=image_image_9_3
)

entry_image_9_1 = PhotoImage(
    file=relative_to_assets_frame9("entry_9_1.png"))
entry_bg_9_1 = canvas9.create_image(
    679.5,
    273.5,
    image=entry_image_9_1
)
entry_9_1 = Entry(
    frame9,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font
)
entry_9_1.place(
    x=532.0,
    y=250.0,
    width=295.0,
    height=45.0
)

button_image_9_2 = PhotoImage(
    file=relative_to_assets_frame9("button_9_2.png"))
button_9_2 = Button(
    frame9,
    image=button_image_9_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: register_account(),
    relief="flat"
)
button_9_2.place(
    x=623.0,
    y=516.0,
    width=119.0,
    height=47.0
)

entry_image_9_2 = PhotoImage(
    file=relative_to_assets_frame9("entry_9_2.png"))
entry_bg_9_2 = canvas9.create_image(
    682.5,
    374.5,
    image=entry_image_9_2
)
entry_9_2 = Entry(
    frame9,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font,
    show="*"
)
entry_9_2.place(
    x=535.0,
    y=351.0,
    width=295.0,
    height=45.0
)

canvas9.create_text(
    527.0,
    416.0,
    anchor="nw",
    text="Re-enter Password",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

entry_image_9_3 = PhotoImage(
    file=relative_to_assets_frame9("entry_9_3.png"))
entry_bg_9_3 = canvas9.create_image(
    679.5,
    472.5,
    image=entry_image_9_3
)
entry_9_3 = Entry(
    frame9,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font,
    show="*"
)
entry_9_3.place(
    x=532.0,
    y=449.0,
    width=295.0,
    height=45.0
)

# Load images for "Hide" and "Show"
hide_icon = PhotoImage(file=relative_to_assets_frame9("button_9_3.png"))
show_icon = PhotoImage(file=relative_to_assets_frame9("button_9_4.png"))

button_9_3 = Button(
    frame9,
    image=hide_icon,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: password_visibility(entry_9_2, button_9_3),
    relief="flat",
    bg="#D9D9D9",
    activebackground="#D9D9D9"
)
button_9_3.place(
    x=799.0,
    y=360.0,
    width=30.0,
    height=30.0
)

button_9_4 = Button(
    frame9,
    image=hide_icon,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: password_visibility(entry_9_3, button_9_4),
    relief="flat",
    bg="#D9D9D9",
    activebackground="#D9D9D9"
)
button_9_4.place(
    x=799.0,
    y=457.0,
    width=30.0,
    height=30.0
)

#FRAME 8
canvas8 = Canvas(
    frame8,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas8.place(x = 0, y = 0)
image_image_8_1 = PhotoImage(
    file=relative_to_assets_frame8("image_8_1.png"))
image_8_1 = canvas8.create_image(
    650.0,
    427.0,
    image=image_image_8_1
)

image_image_8_2 = PhotoImage(
    file=relative_to_assets_frame8("image_8_2.png"))
image_8_2 = canvas8.create_image(
    680.0,
    313.0,
    image=image_image_8_2
)

canvas8.create_text(
    521.0,
    220.0,
    anchor="nw",
    text="Username",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas8.create_text(
    521.0,
    322.0,
    anchor="nw",
    text="Password",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

entry_image_8_1 = PhotoImage(
    file=relative_to_assets_frame8("entry_8_1.png"))
entry_bg_8_1 = canvas8.create_image(
    676.5,
    280.5,
    image=entry_image_8_1
)
entry_8_1 = Entry(
    frame8,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font,
)
entry_8_1.place(
    x=529.0,
    y=257.0,
    width=295.0,
    height=45.0
)

button_image_8_1 = PhotoImage(
    file=relative_to_assets_frame8("button_8_1.png"))
button_8_1 = Button(
    frame8,
    image=button_image_8_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: login_account(),
    relief="flat"
)
button_8_1.place(
    x=634.0,
    y=424.0,
    width=92.0,
    height=47.0
)

entry_image_8_2 = PhotoImage(
    file=relative_to_assets_frame8("entry_8_2.png"))
entry_bg_8_2 = canvas8.create_image(
    679.5,
    382.5,
    image=entry_image_8_2
)
entry_8_2 = Entry(
    frame8,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font,
    show="*"
)
entry_8_2.place(
    x=532.0,
    y=359.0,
    width=295.0,
    height=45.0
)

canvas8.create_text(
    648.906005859375,
    161.550048828125,
    anchor="nw",
    text="Log in",
    fill="#3D3030",
    font=("Inter", 32 * -1)
)

image_image_8_3 = PhotoImage(
    file=relative_to_assets_frame8("image_8_3.png"))
image_8_3 = canvas8.create_image(
    620.0,
    181.0,
    image=image_image_8_3
)

button_image_8_2 = PhotoImage(
    file=relative_to_assets_frame8("button_8_2.png"))
button_8_2 = Button(
    frame8,
    image=button_image_8_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_home(entry_8_1, entry_8_2, button_8_3),
    relief="flat"
)
button_8_2.place(
    x=625.0,
    y=577.0,
    width=103.0,
    height=41.0
)
button_8_3 = Button(
    frame8,
    image=hide_icon,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: password_visibility(entry_8_2, button_8_3),
    relief="flat",
    bg="#D9D9D9",
    activebackground="#D9D9D9"
)
button_8_3.place(
    x=797.0,
    y=368.0,
    width=30.0,
    height=30.0
)

#Frame 7
canvas7 = Canvas(
    frame7,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas7.place(x = 0, y = 0)
image_image_7_1 = PhotoImage(
    file=relative_to_assets_frame7("image_7_1.png"))
image_7_1 = canvas7.create_image(
    650.0,
    427.0,
    image=image_image_7_1
)

button_image_7_1 = PhotoImage(
    file=relative_to_assets_frame7("button_7_1.png"))
button_7_1 = Button(
    frame7,
    image=button_image_7_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: manage_spareparts(),
    relief="flat"
)
button_7_1.place(
    x=458.0,
    y=592.0,
    width=449.0,
    height=73.466796875
)

image_image_7_2 = PhotoImage(
    file=relative_to_assets_frame7("image_7_2.png"))
image_7_2 = canvas7.create_image(
    1114.0,
    63.0,
    image=image_image_7_2
)

button_image_7_2 = PhotoImage(
    file=relative_to_assets_frame7("button_7_2.png"))
button_7_2 = Button(
    frame7,
    image=button_image_7_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame11),
    relief="flat",
    bg="#ffffff",
    activebackground="#ffffff"
)
button_7_2.place(
    x=974.05712890625,
    y=40.449951171875,
    width=44.74345397949219,
    height=46.93333053588867
)

entry_image_7_1 = PhotoImage(
    file=relative_to_assets_frame7("entry_7_1.png"))
entry_bg_7_1 = canvas7.create_image(
    1130.0,
    63.5,
    image=entry_image_7_1
)
label_7_1 = tk.Label(
    frame7,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_7_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

#Frame 6
canvas6 = Canvas(
    frame6,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas6.place(x = 0, y = 0)
image_image_6_1 = PhotoImage(
    file=relative_to_assets_frame6("image_6_1.png"))
image_6_1 = canvas6.create_image(
    650.0,
    427.0,
    image=image_image_6_1
)

image_image_6_2 = PhotoImage(
    file=relative_to_assets_frame6("image_6_2.png"))
image_6_2 = canvas6.create_image(
    1114.0,
    63.0,
    image=image_image_6_2
)

button_image_6_1 = PhotoImage(
    file=relative_to_assets_frame6("button_6_1.png"))
button_6_1 = Button(
    frame6,
    image=button_image_6_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame11),
    relief="flat",
    bg="#ffffff",
    activebackground="#ffffff"
)
button_6_1.place(
    x=974.05712890625,
    y=40.449951171875,
    width=44.74345397949219,
    height=46.93333053588867
)

entry_image_6_1 = PhotoImage(
    file=relative_to_assets_frame6("entry_6_1.png"))
entry_bg_6_1 = canvas6.create_image(
    1130.0,
    63.5,
    image=entry_image_6_1
)
label_6_1 = tk.Label(
    frame6,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_6_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

image_image_6_3 = PhotoImage(
    file=relative_to_assets_frame6("image_6_3.png"))
image_6_3 = canvas6.create_image(
    658.0,
    368.0,
    image=image_image_6_3
)

entry_image_6_2 = PhotoImage(
    file=relative_to_assets_frame6("entry_6_2.png"))
entry_bg_6_2 = canvas6.create_image(
    658.0,
    369.5,
    image=entry_image_6_2
)

button_image_6_2 = PhotoImage(
    file=relative_to_assets_frame6("button_6_2.png"))
button_6_2 = Button(
    frame6,
    image=button_image_6_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_spareparts(),
    relief="flat"
)
button_6_2.place(
    x=113.0,
    y=127.0,
    width=217.0,
    height=41.0
)

button_image_6_3 = PhotoImage(
    file=relative_to_assets_frame6("button_6_3.png"))
button_6_3 = Button(
    frame6,
    image=button_image_6_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: search_item(),
    relief="flat",
    bg="#3E3131",
    activebackground="#3E3131"
)
button_6_3.place(
    x=563.0,
    y=131.0,
    width=100.0,
    height=33.0
)

button_image_6_4 = PhotoImage(
    file=relative_to_assets_frame6("button_6_4.png"))
button_6_4 = Button(
    frame6,
    image=button_image_6_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_back(frame6, frame7, window),
    relief="flat"
)
button_6_4.place(
    x=113.0,
    y=567.0,
    width=97.0,
    height=41.0
)
image_image_6_4 = PhotoImage(
    file=relative_to_assets_frame6("image_6_4.png"))
image_6_4 = canvas6.create_image(
    509.0,
    147.0,
    image=image_image_6_4
)
entry_image_6_3 = PhotoImage(
    file=relative_to_assets_frame6("entry_6_3.png"))
entry_bg_6_3 = canvas6.create_image(
    454.5,
    147.5,
    image=entry_image_6_3
)
entry_6_3 = Entry(
    frame6,
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 12)
)
entry_6_3.place(
    x=361.5,
    y=134.0,
    width=186.0,
    height=25.0
)

canvas6.create_rectangle(
    1154.0,
    720.0,
    1241.0,
    813.0,
    fill="#D9D9D9",
    outline="")

read_alldata()

#Frame 5
canvas5 = Canvas(
    frame5,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas5.place(x = 0, y = 0)
image_image_5_1 = PhotoImage(
    file=relative_to_assets_frame5("image_5_1.png"))
image_5_1 = canvas5.create_image(
    650.0,
    427.0,
    image=image_image_5_1
)

image_image_5_2 = PhotoImage(
    file=relative_to_assets_frame5("image_5_2.png"))
image_5_2 = canvas5.create_image(
    686.0,
    313.0,
    image=image_image_5_2
)

canvas5.create_text(
    346.0,
    152.0,
    anchor="nw",
    text="Item Code",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas5.create_text(
    715.0,
    152.0,
    anchor="nw",
    text="Item Name",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas5.create_text(
    346.0,
    243.0,
    anchor="nw",
    text="Item Type",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas5.create_text(
    346.0,
    331.0,
    anchor="nw",
    text="Item Quantity",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas5.create_text(
    715.0,
    243.0,
    anchor="nw",
    text="Item Price",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas5.create_text(
    715.0,
    331.0,
    anchor="nw",
    text="Description",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

entry_image_5_1 = PhotoImage(
    file=relative_to_assets_frame5("entry_5_1.png"))
entry_bg_5_1 = canvas5.create_image(
    501.5,
    204.5,
    image=entry_image_5_1
)
label_5_2 = tk.Label(
    frame5,
    bg="#D9D9D9",
    fg="#000716",
    font=("Arial", 15)
)
label_5_2.place(
    x=354.0,
    y=181.0,
    width=295.0,
    height=45.0
)

entry_image_5_2 = PhotoImage(
    file=relative_to_assets_frame5("entry_5_2.png"))
entry_bg_5_2 = canvas5.create_image(
    501.5,
    298.5,
    image=entry_image_5_2
)
entry_5_2 = Entry(
    frame5,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font
)
entry_5_2.place(
    x=354.0,
    y=275.0,
    width=295.0,
    height=45.0
)

entry_image_5_3 = PhotoImage(
    file=relative_to_assets_frame5("entry_5_3.png"))
entry_bg_5_3 = canvas5.create_image(
    870.5,
    204.5,
    image=entry_image_5_3
)
entry_5_3 = Entry(
    frame5,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font
)
entry_5_3.place(
    x=723.0,
    y=181.0,
    width=295.0,
    height=45.0
)

button_image_5_1 = PhotoImage(
    file=relative_to_assets_frame5("button_5_1.png"))
button_5_1 = Button(
    frame5,
    image=button_image_5_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_item(),
    relief="flat"
)
button_5_1.place(
    x=346.0,
    y=428.0,
    width=129.0,
    height=47.0
)

entry_image_5_4 = PhotoImage(
    file=relative_to_assets_frame5("entry_5_4.png"))
entry_bg_5_4 = canvas5.create_image(
    870.5,
    420.5,
    image=entry_image_5_4
)
entry_5_4 = Entry(
    frame5,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font
)
entry_5_4.place(
    x=723.0,
    y=366.0,
    width=295.0,
    height=107.0
)

entry_image_5_5 = PhotoImage(
    file=relative_to_assets_frame5("entry_5_5.png"))
entry_bg_5_5 = canvas5.create_image(
    501.5,
    389.5,
    image=entry_image_5_5
)
entry_5_5 = Entry(
    frame5,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font
)
entry_5_5.place(
    x=354.0,
    y=366.0,
    width=295.0,
    height=45.0
)

entry_image_5_6 = PhotoImage(
    file=relative_to_assets_frame5("entry_5_6.png"))
entry_bg_5_6 = canvas5.create_image(
    870.5,
    298.5,
    image=entry_image_5_6
)
entry_5_6 = Entry(
    frame5,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font
)
entry_5_6.place(
    x=723.0,
    y=275.0,
    width=295.0,
    height=45.0
)

button_image_5_2 = PhotoImage(
    file=relative_to_assets_frame5("button_5_2.png"))
button_5_2 = Button(
    frame5,
    image=button_image_5_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_dash(frame5, window),
    relief="flat"
)
button_5_2.place(
    x=320.0,
    y=583.0,
    width=103.0,
    height=41.0
)

button_image_5_3 = PhotoImage(
    file=relative_to_assets_frame5("button_5_3.png"))
button_5_3 = Button(
    frame5,
    image=button_image_5_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_back(frame5, frame6, window),
    relief="flat"
)
button_5_3.place(
    x=435.0,
    y=583.0,
    width=97.0,
    height=41.0
)

image_image_5_3 = PhotoImage(
    file=relative_to_assets_frame5("image_5_3.png"))
image_5_3 = canvas5.create_image(
    1114.0,
    63.0,
    image=image_image_5_3
)

button_image_5_4 = PhotoImage(
    file=relative_to_assets_frame5("button_5_4.png"))
button_5_4 = Button(
    frame5,
    image=button_image_5_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame11),
    relief="flat",
    bg="#ffffff",
    activebackground="#ffffff"
)
button_5_4.place(
    x=974.05712890625,
    y=40.449951171875,
    width=44.74345397949219,
    height=46.93333053588867
)

entry_image_5_7 = PhotoImage(
    file=relative_to_assets_frame5("entry_5_7.png"))
entry_bg_5_7 = canvas5.create_image(
    1130.0,
    63.5,
    image=entry_image_5_7
)
label_5_1 = tk.Label(
    frame5,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_5_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

#Frame 4
canvas4 = Canvas(
    frame4,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas4.place(x = 0, y = 0)
image_image_4_1 = PhotoImage(
    file=relative_to_assets_frame4("image_4_1.png"))
image_4_1 = canvas4.create_image(
    650.0,
    427.0,
    image=image_image_4_1
)

image_image_4_2 = PhotoImage(
    file=relative_to_assets_frame4("image_4_2.png"))
image_4_2 = canvas4.create_image(
    685.0,
    295.0,
    image=image_image_4_2
)

canvas4.create_text(
    526.0,
    218.0,
    anchor="nw",
    text="Item Code",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

entry_image_4_1 = PhotoImage(
    file=relative_to_assets_frame4("entry_4_1.png"))
entry_bg_4_1 = canvas4.create_image(
    681.5,
    277.5,
    image=entry_image_4_1
)
entry_4_1 = Entry(
    frame4,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=entry_font
)
entry_4_1.place(
    x=534.0,
    y=254.0,
    width=295.0,
    height=45.0
)

button_image_4_1 = PhotoImage(
    file=relative_to_assets_frame4("button_4_1.png"))
button_4_1 = Button(
    frame4,
    image=button_image_4_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: search_item(),
    relief="flat"
)
button_4_1.place(
    x=526.0,
    y=318.0,
    width=164.0,
    height=47.0
)

button_image_4_2 = PhotoImage(
    file=relative_to_assets_frame4("button_4_2.png"))
button_4_2 = Button(
    frame4,
    image=button_image_4_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_dash(frame4, window),
    relief="flat"
)
button_4_2.place(
    x=500.0,
    y=582.0,
    width=103.0,
    height=41.0
)

button_image_4_3 = PhotoImage(
    file=relative_to_assets_frame4("button_4_3.png"))
button_4_3 = Button(
    frame4,
    image=button_image_4_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_back(frame4, frame6, window),
    relief="flat"
)
button_4_3.place(
    x=615.0,
    y=582.0,
    width=97.0,
    height=41.0
)

image_image_4_3 = PhotoImage(
    file=relative_to_assets_frame4("image_4_3.png"))
image_4_3 = canvas4.create_image(
    1114.0,
    63.0,
    image=image_image_4_3
)

button_image_4_4 = PhotoImage(
    file=relative_to_assets_frame4("button_4_4.png"))
button_4_4 = Button(
    frame4,
    image=button_image_4_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame11),
    relief="flat",
    bg="#ffffff",
    activebackground="#ffffff"
)
button_4_4.place(
    x=974.05712890625,
    y=40.4501953125,
    width=44.74345397949219,
    height=46.93333053588867
)

entry_image_4_2 = PhotoImage(
    file=relative_to_assets_frame4("entry_4_2.png"))
entry_bg_4_2 = canvas4.create_image(
    1130.0,
    63.5,
    image=entry_image_4_2
)
label_4_1 = tk.Label(
    frame4,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_4_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

#Frame 3
canvas3 = Canvas(
    frame3,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas3.place(x = 0, y = 0)
image_image_3_1 = PhotoImage(
    file=relative_to_assets_frame3("image_3_1.png"))
image_3_1 = canvas3.create_image(
    650.0,
    427.0,
    image=image_image_3_1
)

image_image_3_2 = PhotoImage(
    file=relative_to_assets_frame3("image_3_2.png"))
image_3_2 = canvas3.create_image(
    675.0,
    313.0,
    image=image_image_3_2
)

canvas3.create_text(
    335.0,
    152.0,
    anchor="nw",
    text="Item Code",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas3.create_text(
    704.0,
    152.0,
    anchor="nw",
    text="Item Name",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas3.create_text(
    335.0,
    243.0,
    anchor="nw",
    text="Item Type",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas3.create_text(
    335.0,
    331.0,
    anchor="nw",
    text="Item Quintity",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas3.create_text(
    704.0,
    243.0,
    anchor="nw",
    text="Item Price",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas3.create_text(
    704.0,
    331.0,
    anchor="nw",
    text="Description",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

entry_image_3_1 = PhotoImage(
    file=relative_to_assets_frame3("entry_3_1.png"))
entry_bg_3_1 = canvas3.create_image(
    490.5,
    204.5,
    image=entry_image_3_1
)
label_3_2 = tk.Label(
    frame3,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
label_3_2.place(
    x=343.0,
    y=181.0,
    width=295.0,
    height=45.0
)

entry_image_3_2 = PhotoImage(
    file=relative_to_assets_frame3("entry_3_2.png"))
entry_bg_3_2 = canvas3.create_image(
    490.5,
    298.5,
    image=entry_image_3_2
)
label_3_3 = tk.Label(
    frame3,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
label_3_3.place(
    x=343.0,
    y=275.0,
    width=295.0,
    height=45.0
)

entry_image_3_3 = PhotoImage(
    file=relative_to_assets_frame3("entry_3_3.png"))
entry_bg_3_3 = canvas3.create_image(
    859.5,
    204.5,
    image=entry_image_3_3
)
label_3_4 = tk.Label(
    frame3,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
label_3_4.place(
    x=712.0,
    y=181.0,
    width=295.0,
    height=45.0
)

button_image_3_1 = PhotoImage(
    file=relative_to_assets_frame3("button_3_1.png"))
button_3_1 = Button(
    frame3,
    image=button_image_3_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame2),
    relief="flat"
)
button_3_1.place(
    x=335.0,
    y=428.0,
    width=145.0,
    height=47.0
)

button_image_3_2 = PhotoImage(
    file=relative_to_assets_frame3("button_3_2.png"))
button_3_2 = Button(
    frame3,
    image=button_image_3_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: delete_item(),
    relief="flat"
)
button_3_2.place(
    x=500.0,
    y=428.0,
    width=145.0,
    height=47.0
)

entry_image_3_4 = PhotoImage(
    file=relative_to_assets_frame3("entry_3_4.png"))
entry_bg_3_4 = canvas3.create_image(
    859.5,
    420.5,
    image=entry_image_3_4
)
label_3_5 = tk.Label(
    frame3,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
label_3_5.place(
    x=712.0,
    y=366.0,
    width=295.0,
    height=107.0
)

entry_image_3_5 = PhotoImage(
    file=relative_to_assets_frame3("entry_3_5.png"))
entry_bg_3_5 = canvas3.create_image(
    490.5,
    389.5,
    image=entry_image_3_5
)
label_3_6 = tk.Label(
    frame3,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
label_3_6.place(
    x=343.0,
    y=366.0,
    width=295.0,
    height=45.0
)

entry_image_3_6 = PhotoImage(
    file=relative_to_assets_frame3("entry_3_6.png"))
entry_bg_3_6 = canvas3.create_image(
    859.5,
    298.5,
    image=entry_image_3_6
)
label_3_7 = tk.Label(
    frame3,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
label_3_7.place(
    x=712.0,
    y=275.0,
    width=295.0,
    height=45.0
)

button_image_3_3 = PhotoImage(
    file=relative_to_assets_frame3("button_3_3.png"))
button_3_3 = Button(
    frame3,
    image=button_image_3_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame7),
    relief="flat"
)
button_3_3.place(
    x=312.0,
    y=576.0,
    width=103.0,
    height=41.0
)

button_image_3_4 = PhotoImage(
    file=relative_to_assets_frame3("button_3_4.png"))
button_3_4 = Button(
    frame3,
    image=button_image_3_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame6),
    relief="flat"
)
button_3_4.place(
    x=427.0,
    y=576.0,
    width=97.0,
    height=41.0
)

image_image_3_3 = PhotoImage(
    file=relative_to_assets_frame3("image_3_3.png"))
image_3_3 = canvas3.create_image(
    1114.0,
    63.0,
    image=image_image_3_3
)

button_image_3_5 = PhotoImage(
    file=relative_to_assets_frame3("button_3_5.png"))
button_3_5 = Button(
    frame3,
    image=button_image_3_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame11),
    relief="flat",
    bg="#ffffff",
    activebackground="#ffffff"
)
button_3_5.place(
    x=974.05712890625,
    y=40.4501953125,
    width=44.74345397949219,
    height=46.93333053588867
)

entry_image_3_7 = PhotoImage(
    file=relative_to_assets_frame3("entry_3_7.png"))
entry_bg_3_7 = canvas3.create_image(
    1130.0,
    63.5,
    image=entry_image_3_7
)
label_3_1 = tk.Label(
    frame3,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_3_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

#Frame 2
canvas2 = Canvas(
    frame2,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas2.place(x = 0, y = 0)
image_image_2_1 = PhotoImage(
    file=relative_to_assets_frame2("image_2_1.png"))
image_2_1 = canvas2.create_image(
    650.0,
    427.0,
    image=image_image_2_1
)

image_image_2_2 = PhotoImage(
    file=relative_to_assets_frame2("image_2_2.png"))
image_2_2 = canvas2.create_image(
    675.0,
    313.0,
    image=image_image_2_2
)

canvas2.create_text(
    335.0,
    152.0,
    anchor="nw",
    text="Item Code",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas2.create_text(
    704.0,
    152.0,
    anchor="nw",
    text="Item Name",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas2.create_text(
    335.0,
    243.0,
    anchor="nw",
    text="Item Type",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas2.create_text(
    335.0,
    331.0,
    anchor="nw",
    text="Item Quintity",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas2.create_text(
    704.0,
    243.0,
    anchor="nw",
    text="Item Price",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas2.create_text(
    704.0,
    331.0,
    anchor="nw",
    text="Description",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

entry_image_2_1 = PhotoImage(
    file=relative_to_assets_frame2("entry_2_1.png"))
entry_bg_2_1 = canvas2.create_image(
    490.5,
    204.5,
    image=entry_image_2_1
)
label_2_2 = tk.Label(
    frame2,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
label_2_2.place(
    x=343.0,
    y=181.0,
    width=295.0,
    height=45.0
)

entry_image_2_2 = PhotoImage(
    file=relative_to_assets_frame2("entry_2_2.png"))
entry_bg_2_2 = canvas2.create_image(
    490.5,
    298.5,
    image=entry_image_2_2
)
entry_2_2 = Entry(
    frame2,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
entry_2_2.place(
    x=343.0,
    y=275.0,
    width=295.0,
    height=45.0
)

entry_image_2_3 = PhotoImage(
    file=relative_to_assets_frame2("entry_2_3.png"))
entry_bg_2_3 = canvas2.create_image(
    859.5,
    204.5,
    image=entry_image_2_3
)
entry_2_3 = Entry(
    frame2,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
entry_2_3.place(
    x=712.0,
    y=181.0,
    width=295.0,
    height=45.0
)

button_image_2_1 = PhotoImage(
    file=relative_to_assets_frame2("button_2_1.png"))
button_2_1 = Button(
    frame2,
    image=button_image_2_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_item(),
    relief="flat"
)
button_2_1.place(
    x=418.0,
    y=428.0,
    width=145.0,
    height=47.0
)

entry_image_2_4 = PhotoImage(
    file=relative_to_assets_frame2("entry_2_4.png"))
entry_bg_2_4 = canvas2.create_image(
    859.5,
    420.5,
    image=entry_image_2_4
)
entry_2_4 = Entry(
    frame2,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
entry_2_4.place(
    x=712.0,
    y=366.0,
    width=295.0,
    height=107.0
)

entry_image_2_5 = PhotoImage(
    file=relative_to_assets_frame2("entry_2_5.png"))
entry_bg_2_5 = canvas2.create_image(
    490.5,
    389.5,
    image=entry_image_2_5
)
entry_2_5 = Entry(
    frame2,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
entry_2_5.place(
    x=343.0,
    y=366.0,
    width=295.0,
    height=45.0
)

entry_image_2_6 = PhotoImage(
    file=relative_to_assets_frame2("entry_2_6.png"))
entry_bg_2_6 = canvas2.create_image(
    859.5,
    298.5,
    image=entry_image_2_6
)
entry_2_6 = Entry(
    frame2,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
entry_2_6.place(
    x=712.0,
    y=275.0,
    width=295.0,
    height=45.0
)

image_image_2_3 = PhotoImage(
    file=relative_to_assets_frame2("image_2_3.png"))
image_2_3 = canvas2.create_image(
    1114.0,
    63.0,
    image=image_image_2_3
)

button_image_2_2 = PhotoImage(
    file=relative_to_assets_frame2("button_2_2.png"))
button_2_2 = Button(
    frame2,
    image=button_image_2_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame11),
    relief="flat",
    bg="#ffffff",
    activebackground="#ffffff"
)
button_2_2.place(
    x=974.05712890625,
    y=40.4501953125,
    width=44.74345397949219,
    height=46.93333053588867
)

entry_image_2_7 = PhotoImage(
    file=relative_to_assets_frame2("entry_2_7.png"))
entry_bg_2_7 = canvas2.create_image(
    1130.0,
    63.5,
    image=entry_image_2_7
)
label_2_1 = tk.Label(
    frame2,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_2_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

button_image_2_3 = PhotoImage(
    file=relative_to_assets_frame2("button_2_3.png"))
button_2_3 = Button(
    frame2,
    image=button_image_2_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_back(frame2, frame3, window),
    relief="flat"
)
button_2_3.place(
    x=309.0,
    y=583.0,
    width=97.0,
    height=41.0
)

#Frame 1
canvas1 = Canvas(
    frame1,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas1.place(x = 0, y = 0)
image_image_1_1 = PhotoImage(
    file=relative_to_assets_frame1("image_1_1.png"))
image_1_1 = canvas1.create_image(
    650.0,
    427.0,
    image=image_image_1_1
)

image_image_1_2 = PhotoImage(
    file=relative_to_assets_frame1("image_1_2.png"))
image_1_2 = canvas1.create_image(
    685.0,
    363.0,
    image=image_image_1_2
)

button_image_1_1 = PhotoImage(
    file=relative_to_assets_frame1("button_1_1.png"))
button_1_1 = Button(
    frame1,
    image=button_image_1_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame0),
    relief="flat"
)
button_1_1.place(
    x=501.0,
    y=522.0,
    width=176.2763671875,
    height=47.0
)

button_image_1_2 = PhotoImage(
    file=relative_to_assets_frame1("button_1_2.png"))
button_1_2 = Button(
    frame1,
    image=button_image_1_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: delete_account(),
    relief="flat"
)
button_1_2.place(
    x=692.0,
    y=522.0,
    width=176.27999877929688,
    height=47.0
)

canvas1.create_text(
    501.0,
    313.0,
    anchor="nw",
    text="Username",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas1.create_text(
    501.0,
    415.0,
    anchor="nw",
    text="Password",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

entry_image_1_1 = PhotoImage(
    file=relative_to_assets_frame1("entry_1_1.png"))
entry_bg_1_1 = canvas1.create_image(
    684.5,
    373.5,
    image=entry_image_1_1
)
label_1_3 = tk.Label(
    frame1,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
label_1_3.place(
    x=509.0,
    y=350.0,
    width=351.0,
    height=45.0
)

entry_image_1_2 = PhotoImage(
    file=relative_to_assets_frame1("entry_1_2.png"))
entry_bg_1_2 = canvas1.create_image(
    684.5,
    475.5,
    image=entry_image_1_2
)
label_1_2 = tk.Label(
    frame1,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15),
)
label_1_2.place(
    x=509.0,
    y=452.0,
    width=351.0,
    height=45.0
)

canvas1.create_text(
    629.0,
    258.0,
    anchor="nw",
    text="Profile",
    fill="#3D3030",
    font=("Inter", 32 * -1)
)

image_image_1_3 = PhotoImage(
    file=relative_to_assets_frame1("image_1_3.png"))
image_1_3 = canvas1.create_image(
    680.0,
    202.0,
    image=image_image_1_3
)

image_image_1_4 = PhotoImage(
    file=relative_to_assets_frame1("image_1_4.png"))
image_1_4 = canvas1.create_image(
    1114.0,
    63.0,
    image=image_image_1_4
)

image_image_1_5 = PhotoImage(
    file=relative_to_assets_frame1("image_1_5.png"))
image_1_5 = canvas1.create_image(
    996.05712890625,
    63.4501953125,
    image=image_image_1_5
)

entry_image_1_3 = PhotoImage(
    file=relative_to_assets_frame1("entry_1_3.png"))
entry_bg_1_3 = canvas1.create_image(
    1130.0,
    63.5,
    image=entry_image_1_3
)
label_1_1 = tk.Label(
    frame1,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_1_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

button_image_1_3 = PhotoImage(
    file=relative_to_assets_frame1("button_1_3.png"))
button_1_3 = Button(
    frame1,
    image=button_image_1_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame7),
    relief="flat"
)
button_1_3.place(
    x=476.0,
    y=612.0,
    width=103.0,
    height=41.0
)

button_image_1_4 = PhotoImage(
    file=relative_to_assets_frame1("button_1_4.png"))
button_1_4 = Button(
    frame1,
    image=button_image_1_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame11),
    relief="flat"
)
button_1_4.place(
    x=591.0,
    y=612.0,
    width=97.0,
    height=41.0
)

#Frame 0
canvas0 = Canvas(
    frame0,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas0.place(x = 0, y = 0)
image_image_0_1 = PhotoImage(
    file=relative_to_assets_frame0("image_0_1.png"))
image_0_1 = canvas0.create_image(
    650.0,
    427.0,
    image=image_image_0_1
)

image_image_0_2 = PhotoImage(
    file=relative_to_assets_frame0("image_0_2.png"))
image_0_2 = canvas0.create_image(
    685.0,
    363.0,
    image=image_image_0_2
)

button_image_0_1 = PhotoImage(
    file=relative_to_assets_frame0("button_0_1.png"))
button_0_1 = Button(
    frame0,
    image=button_image_0_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_account(),
    relief="flat"
)
button_0_1.place(
    x=592.0,
    y=520.0,
    width=176.2763671875,
    height=47.0
)

canvas0.create_text(
    501.0,
    313.0,
    anchor="nw",
    text="Username",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

canvas0.create_text(
    501.0,
    415.0,
    anchor="nw",
    text="Password",
    fill="#3D3030",
    font=("Inter", 24 * -1)
)

entry_image_0_1 = PhotoImage(
    file=relative_to_assets_frame0("entry_0_1.png"))
entry_bg_0_1 = canvas0.create_image(
    684.5,
    373.5,
    image=entry_image_0_1
)
entry_0_1 = Entry(
    frame0,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
entry_0_1.place(
    x=509.0,
    y=350.0,
    width=351.0,
    height=45.0
)

entry_image_0_2 = PhotoImage(
    file=relative_to_assets_frame0("entry_0_2.png"))
entry_bg_0_2 = canvas0.create_image(
    684.5,
    475.5,
    image=entry_image_0_2
)
entry_0_2 = Entry(
    frame0,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Arial", 15)
)
entry_0_2.place(
    x=509.0,
    y=452.0,
    width=351.0,
    height=45.0
)

canvas0.create_text(
    629.0,
    258.0,
    anchor="nw",
    text="Profile",
    fill="#3D3030",
    font=("Inter", 32 * -1)
)

image_image_0_3 = PhotoImage(
    file=relative_to_assets_frame0("image_0_3.png"))
image_0_3 = canvas0.create_image(
    680.0,
    202.0,
    image=image_image_0_3
)

image_image_0_4 = PhotoImage(
    file=relative_to_assets_frame0("image_0_4.png"))
image_0_4 = canvas0.create_image(
    1114.0,
    63.0,
    image=image_image_0_4
)

image_image_0_5 = PhotoImage(
    file=relative_to_assets_frame0("image_0_5.png"))
image_0_5 = canvas0.create_image(
    996.05712890625,
    63.4501953125,
    image=image_image_0_5
)

entry_image_0_3 = PhotoImage(
    file=relative_to_assets_frame0("entry_0_3.png"))
entry_bg_0_3 = canvas0.create_image(
    1130.0,
    63.5,
    image=entry_image_0_3
)
label_0_1 = tk.Label(
    frame0,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_0_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

button_image_0_2 = PhotoImage(
    file=relative_to_assets_frame0("button_0_2.png"))
button_0_2 = Button(
    frame0,
    image=button_image_0_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: go_back(frame0, frame1, window),
    relief="flat"
)
button_0_2.place(
    x=480.0,
    y=617.0,
    width=97.0,
    height=41.0
)

button_0_3 = Button(
    frame0,
    image=hide_icon,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: password_visibility(entry_0_2, button_0_3),
    relief="flat",
    bg="#D9D9D9",
    activebackground="#D9D9D9"
)
button_0_3.place(
    x=830.0,
    y=462.0,
    width=30.0,
    height=30.0
)

#Frame 11
canvas11 = Canvas(
    frame11,
    bg = "#FFFFFF",
    height = 720,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas11.place(x = 0, y = 0)
image_image_11_1 = PhotoImage(
    file=relative_to_assets_frame11("image_11_1.png"))
image_11_1 = canvas11.create_image(
    650.0,
    427.0,
    image=image_image_11_1
)

image_image_11_2 = PhotoImage(
    file=relative_to_assets_frame11("image_11_2.png"))
image_11_2 = canvas11.create_image(
    685.0,
    294.0,
    image=image_image_11_2
)

button_image_11_1 = PhotoImage(
    file=relative_to_assets_frame11("button_11_1.png"))
button_11_1 = Button(
    frame11,
    image=button_image_11_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: logout_account(),
    relief="flat"
)
button_11_1.place(
    x=633.0,
    y=378.0,
    width=94.0,
    height=47.0
)

button_image_11_2 = PhotoImage(
    file=relative_to_assets_frame11("button_11_2.png"))
button_11_2 = Button(
    frame11,
    image=button_image_11_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame1),
    relief="flat",
    bg="#ffffff",
    activebackground="#ffffff"
)
button_11_2.place(
    x=610.0,
    y=158.0,
    width=149.38330078125,
    height=133.6082763671875
)

image_image_11_3 = PhotoImage(
    file=relative_to_assets_frame11("image_11_3.png"))
image_11_3 = canvas11.create_image(
    1114.0,
    63.0,
    image=image_image_11_3
)

image_image_11_4 = PhotoImage(
    file=relative_to_assets_frame11("image_11_4.png"))
image_11_4 = canvas11.create_image(
    996.05712890625,
    63.4501953125,
    image=image_image_11_4
)

entry_image_11_1 = PhotoImage(
    file=relative_to_assets_frame11("entry_11_1.png"))
entry_bg_11_1 = canvas11.create_image(
    1130.0,
    63.5,
    image=entry_image_11_1
)
label_11_1 = tk.Label(
    frame11,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 15)
)
label_11_1.place(
    x=1019.0,
    y=47.0,
    width=222.0,
    height=31.0
)

entry_image_11_2 = PhotoImage(
    file=relative_to_assets_frame11("entry_11_2.png"))
entry_bg_11_2 = canvas11.create_image(
    684.5,
    335.0,
    image=entry_image_11_2
)
label_11_2 = tk.Label(
    frame11,
    bg="#FFFFFF",  # Set the background color
    fg="#000716",  # Set the foreground (text) color
    font=("Arial", 25)
)
label_11_2.place(
    x=543.0,
    y=306.0,
    width=283.0,
    height=56.0
)

button_image_11_3 = PhotoImage(
    file=relative_to_assets_frame11("button_11_3.png"))
button_11_3 = Button(
    frame11,
    image=button_image_11_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_frame(frame7),
    relief="flat"
)
button_11_3.place(
    x=633.0,
    y=581.0,
    width=103.0,
    height=41.0
)

# Start with frame10 visible
show_frame(frame10)

window.resizable(True, True)
window.mainloop()
